-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 18:47:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ongacme` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ongacme` DEFAULT CHARACTER SET utf8 ;
USE `ongacme` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`user` (
  `id_cliiente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20),
  `cep` VARCHAR(45),
  `estado` VARCHAR(2),
  `cidade` VARCHAR(45),
  `bairro` VARCHAR(45),
  `endereco` VARCHAR(45),
  `numero` VARCHAR(45),
  `renda_familiar` DECIMAL(10,2),
  `texto_solicitacao` VARCHAR(1000),
  PRIMARY KEY (`id_cliiente`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`parceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`parceiros` (
  `id_parceiro` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(32),
  `cnpj` VARCHAR(50),
  `responsavel` VARCHAR(45),
  `cep` VARCHAR(45),
  `estado` VARCHAR(45),
  `cidade` VARCHAR(45),
  `endereco` VARCHAR(45),
  `numero` VARCHAR(45),
  `bairro` VARCHAR(45),
  `descricao` VARCHAR(45),
  `logo` VARCHAR(45),
  PRIMARY KEY (`id_parceiro`));


-- -----------------------------------------------------
-- Table `mydb`.`solicitacoes_ac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`solicitacoes_ac` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255),
  `email` VARCHAR(255),
  `telefone` VARCHAR(20),
  `cep` VARCHAR(45),
  `estado` VARCHAR(2),
  `cidade` VARCHAR(45),
  `bairro` VARCHAR(45),
  `endereco` VARCHAR(45),
  `numero` VARCHAR(45),
  `renda_familiar` DECIMAL(10,2),
  `texto_solicitacao` VARCHAR(1000),
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`solicitacoes_rec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`solicitacoes_rec` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255),
  `email` VARCHAR(255),
  `telefone` VARCHAR(20),
  `cep` VARCHAR(45),
  `estado` VARCHAR(2),
  `cidade` VARCHAR(45),
  `bairro` VARCHAR(45),
  `endereco` VARCHAR(45),
  `numero` VARCHAR(45),
  `renda_familiar` DECIMAL(10,2),
  `texto_solicitacao` VARCHAR(1000),
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`imagens` (
  `id_imagem` INT NOT NULL,
  `nome_imagem` VARCHAR(255),
  PRIMARY KEY (`id_imagem`));


-- -----------------------------------------------------
-- Table `mydb`.`dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`dependentes` (
  `id_dependente` INT NOT NULL,
  `id_cliente` VARCHAR(255) NOT NULL,
  `nome_dependente` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `renda_dependente` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_dependente`),
  INDEX `cliente_depen_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `cliente_depen`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ongacme`.`user` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`textos` (
  `id_texto` INT NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id_texto`));


-- -----------------------------------------------------
-- Table `mydb`.`encaminhados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ongacme`.`encaminhados` (
  `id_encaminhado` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_parceiro` INT NOT NULL,
  PRIMARY KEY (`id_encaminhado`),
  INDEX `parceiro_enc_idx` (`id_parceiro` ASC) VISIBLE,
  INDEX `cliente_enc_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `parceiro_enc`
    FOREIGN KEY (`id_parceiro`)
    REFERENCES `ongacme`.`parceiros` (`id_parceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_enc`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ongacme`.`user` (`id_cliiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
